---
  common:
    assetsRoot: './assets'
  chapters:
    - {}
    - {}
    - resourcesUrl: "https://www.dropbox.com/s/0oe92zziik5mwhf/opencv_bootcamp_assets_NB4.zip?dl=1"
      resourcesFileName: "opencv_bootcamp_assets_NB4.zip"
    - {}
